### ISSUE TITLE
Cannot install SparseArray with R 4.4 and BiocManager 3.19

### ISSUE THREAD

**Issue by esraaelmligy** [Bioconductor/SparseArray#10] opened 2024-05-07 08:58 UTC
Hello, i need SparseArray as a dependency for another package i am trying to install, but upon trying to fetch it from bioconductor it gives the following error: 

**> BiocManager::install("SparseArray")**
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.19 (BiocManager 1.30.23), R 4.4.0 (2024-04-24)
Installing package(s) 'SparseArray'
trying URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘SparseArray’ failed
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    codetools, lattice, MASS, Matrix, nlme, survival
    
So i tried to install it from github using remotes but upon compilation it gives the following error:

Rvector_utils.c: In function ‘_set_selected_Rsubvec_elts_to_zero’:
Rvector_utils.c:400:3: error: a label can only be part of a statement and a declaration is not a statement
  400 |   SEXP zero = PROTECT(mkChar(""));
      |   ^~~~
make: *** [/usr/lib/R/etc/Makeconf:195: Rvector_utils.o] Error 1

So, what shall i do to install the package?

**Comment by vjcitn** [comment] 2024-05-07 09:33
I can't reproduce the problem with BiocManager::install at this time.  There can be intermittent web access problems.  Try again and if it fails, please report the output of sessionInfo() for your session.

**Comment by esraaelmligy** [comment] 2024-05-07 10:03
I just tried again and it still fails, here is the session info

> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=ar_EG.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=ar_EG.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=ar_EG.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ar_EG.UTF-8 LC_IDENTIFICATION=C       

time zone: Africa/Cairo
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.23 compiler_4.4.0      tools_4.4.0       


and the error

> BiocManager::install("SparseArray")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.19 (BiocManager 1.30.23), R 4.4.0 (2024-04-24)
Installing package(s) 'SparseArray'
trying URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/SparseArray_1.4.0.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘SparseArray’ failed
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    codetools, lattice, MASS, Matrix, nlme, survival

**Comment by vjcitn** [comment] 2024-05-07 10:20
Some more knowledgeable folks will be coming on line soon and will help you make the necessary connection.

**Comment by lshep** [comment] 2024-05-07 10:50
Likely caching issue again that we are working on resolving.  I'll run the manual fix as we finish discussing the correct resolution today.  Note the version available should be 1.4.1 https://bioconductor.org/checkResults/release/bioc-LATEST/SparseArray/

**Comment by lshep** [comment] 2024-05-07 10:52
I just reset the cache.  Could you please try again and see if the issue persists.

**Comment by hpages** [comment] 2024-05-07 14:53
As for the compilation error ("a label can only be part of a statement and a declaration is not a statement", only seen with some rare compilers), it should be fixed in **SparseArray** version 1.4.3 (`RELEASE_3_19` branch) and 1.5.3 (`devel` branch).

**Comment by esraaelmligy** [comment] 2024-05-08 08:42
Thank you so much for helping! I am now able to install it with no errors.

**Comment by vjcitn** [comment] 2024-05-08 09:46
Great!

**Closed as completed by vjcitn** 2024-05-08 09:46 UTC
